# `numpy`

* `numpy` je knižnica na vedecké výpočty v Pythone
* Podporuje:
    * vektory a matice
    * lineárnu algebru (riešenie systémov rovníc)
    * vykresľovanie (cez knižnicu `matplotlib`)
* V princípe funguje podobne ako MATLAB

## Dôležité odkazy

* Hlavná stránka: http://www.numpy.org
* `numpy` pre používateľov MATLABu: https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html
* Tutoriál pre `numpy`: https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

## Importovanie knižnice `numpy`

* Dlhý zápis:
```
import numpy
vektor = numpy.funkcia(...)
```

* Skrátený zápis:
```
import numpy as np
vektor = np.funkcia(...)
```

## Vektory a matice

* Vektory a matice v `numpy` sú reprezentované triedou `array`.
* Oboje je reprezentované zoznamom zoznamov
    * vonkajší zoznam definuje riadky
    * vnútorný zoznam definuje stĺpce
* Riadkový vektor 1x3:
```
v1 = np.array( [ [1., 2., 3.] ] )
```
* Stĺpcový vektor 3x1:
```
v2 = np.array( [ [1.], [2.], [3.] ] )
```
* Matica 2x3:
```
m = np.array( [ [1., 2., 3.], [4., 5., 6.] ] )
```

In [1]:
import numpy as np
v1 = np.array( [ [1., 2., 3.] ] )
v2 = np.array( [ [1.], [2.], [3.] ] )
m = np.array( [ [1., 2., 3.], [4., 5., 6.] ] )
print(v1)
print(v2)
print(m)

[[ 1.  2.  3.]]
[[ 1.]
 [ 2.]
 [ 3.]]
[[ 1.  2.  3.]
 [ 4.  5.  6.]]


## Vypisovanie vektorov a matíc

* Vypisovanie vektorov a matíc sa realizuje cez `print()`

In [92]:
import numpy as np
v1 = np.array([[1., 2., 3.]])
v2 = np.array([[1.], [2.], [3.]])
m = np.array([ [1., 2., 3.], [4., 5., 6.] ])
print('Riadkovy vektor:')
print(v1)
print('\nStlpcovy vektor:')
print(v2)
print('\nMatica:')
print(m)
print('Vektor je %s' % (v2))
print('Matica je {}'.format(m))

Riadkovy vektor:
[[ 1.  2.  3.]]

Stlpcovy vektor:
[[ 1.]
 [ 2.]
 [ 3.]]

Matica:
[[ 1.  2.  3.]
 [ 4.  5.  6.]]
Vektor je [[ 1.]
 [ 2.]
 [ 3.]]
Matica je [[ 1.  2.  3.]
 [ 4.  5.  6.]]


## Zistenie veľkosti 

* Atribút `shape` obsahuje riadkovú a stĺpcovú veľkosť
* Vracia dvojicu, ktorú je možné "rozbaliť":
```
riadky, stlpce = v1.shape
print('v1 ma {} riadkov a {} stlpcov'.format(riadky, stlpce))
```
* Atribút `size` obsahuje počet prvkov:
```
pocet = m.size
print('Matica ma %d prvkov' % pocet)
```

In [93]:
riadky, stlpce = v1.shape
print('v1 ma {} riadkov a {} stlpcov'.format(riadky, stlpce))
pocet = m.size
print('Matica ma %d prvkov' % pocet)

v1 ma 1 riadkov a 3 stlpcov
Matica ma 6 prvkov


## Tvorba špeciálnych matíc

* Nulovú maticu vytvoríme funkciou `zeros`
* Vstupom je dvojica (počet riadkov a počet stĺpcov)
```
nulova = np.zeros( (3, 4) )
print(nulova)
```
* Maticu jednotiek vytvoríme funkciou `ones`
```
jednotky = np.ones( (2, 1) )
```
* Jednotkovú maticu vytvoríme funkciou `eye`
```
I = np.eye(3)
```

In [27]:
nulova = np.zeros( (3, 4) )
jednotky = np.ones( (2, 1) )
I = np.eye(3)
print(nulova)
print(jednotky)
print(I)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.]
 [ 1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## Indexovanie a rezanie

* Vektory a matice indexujeme ako zoznamy
* Nezabudnite, že Python indexuje od nuly
```
M = np.array( [ [1., 2., 3.], [4., 5., 6.] ])
print(M[0, 0])
```
* Posledný riadok/stĺpec majú index -1
```
print(M[-1, -1])
```
* Vektor a maticu je možné "rozrezať" na časti:
```
M = np.array( [ [1., 2., 3.], [4., 5., 6.] ])
prvy_riadok = M[0, :]
print(prvy_riadok)
```

In [40]:
M = np.array( [ [1., 2., 3.], [4., 5., 6.] ])
V = np.array( [[1., 2., 3.]])
W = np.array( [ [1.], [2.], [3.] ])
print(M[0, 0])
print(M[-1, -1])
print(V[0, 1])

1.0
6.0
2.0


In [77]:
M = np.array( [ [1., 2., 3.], [4., 5., 6.] ])
prvy_riadok = M[0, :]
print(prvy_riadok)
prvy_riadok = M[0, :]
print(prvy_riadok)

[ 1.  2.  3.]
[ 1.  2.  3.]


## Kopírovanie

* Priradenie `y = x` vytvára iba odkaz!
```
x = np.array( [ [1.] ] )
y = x
y[0, 0] = 2
```
* Kópia vektora/matice sa spraví cez `copy()':
```
y = x.copy()
y[0] = 3
```

In [67]:
x = np.array( [ [1.] ] )
y = x
y[0, 0] = 2
print(x, y)

y = x.copy()
y[0] = 3
print(x, y)

[[ 2.]] [[ 2.]]
[[ 2.]] [[ 3.]]


## Poznámka k indexovaniu a rezaniu

* Pri indexovaní a rezaní sa vracia pohľad (view)
* Pri zmene pohľadu sa mení aj pôvodný objekt:
```
M = np.array([ [ 1., 2., 3. ] ])
p = M[0, 1:3]
p[1] = 4
```
* Ak chceme modifikovať iba pohľad, musíme ho kopírovať:
```
q = M[0, 1:3].copy()
q[1] = 5
```

In [90]:
M = np.array([ [ 1., 2., 3. ] ])
p = M[0, 1:3]
print(p)
p[1] = 4
print(p)
print(M)
q = M[0, 1:3].copy()
q[1] = 5
print(q)
print(M)

[ 2.  3.]
[ 2.  4.]
[[ 1.  2.  4.]]
[ 2.  5.]
[[ 1.  2.  4.]]


## Matematické funkcie

* Transpozícia vektora/matice:
```
M = np.array( [ [1., 2., 3.], [4., 5., 6.] ])
trans = M.transpose()
```
* Transpozícia vektora/matice::
```
trans = M.T
```
* Násobenie vektorov a matíc (musia sedieť rozmery):
```
M = np.array( [ [1., 2., 3.], [4., 5., 6.] ])
V = np.array( [ [1.], [2.], [3.] ])
Z = M.dot(V)
```

In [51]:
M = np.array( [ [1., 2., 3.], [4., 5., 6.] ])
trans = M.transpose()
print(trans)
M = np.array( [ [1., 2., 3.], [4., 5., 6.] ])
V = np.array( [ [1.], [2.], [3.] ])
Z = M.dot(V)
print(Z)

[[ 1.  4.]
 [ 2.  5.]
 [ 3.  6.]]
[[ 14.]
 [ 32.]]


## Operácie po prvkoch

* Sčitovanie, odčitovanie, násobenie, delenie:
```
M1 = np.array( [ [1., 2., 3.], [4., 5., 6.] ])
M2 = np.array( [ [7., 8., 9.], [10., 11., 12.] ])
Q1 = M1 + M2
Q2 = M1 - M2
Q3 = M1 * M2
Q4 = M1 / M2
```
* Umocnenie každého prvku:
```
Q5 = M1**3
```
* Vyhľadávanie
```
idx = M1>3.5
```

In [97]:
M1 = np.array( [ [1., 2., 3.], [4., 5., 6.] ])
M2 = np.array( [ [7., 8., 9.], [10., 11., 12.] ])
print(M1+M2)
print(M1-M2)
print(M1*M2)
print(M1/M2)
print(M1**3)
print(M1>3.5)
print(np.nonzero(M1>2.5))
print(M1*2)
#print(M1[np.nonzero(M1>2.5)])

[[  8.  10.  12.]
 [ 14.  16.  18.]]
[[-6. -6. -6.]
 [-6. -6. -6.]]
[[  7.  16.  27.]
 [ 40.  55.  72.]]
[[ 0.14285714  0.25        0.33333333]
 [ 0.4         0.45454545  0.5       ]]
[[   1.    8.   27.]
 [  64.  125.  216.]]
[[False False False]
 [ True  True  True]]
(array([0, 1, 1, 1]), array([2, 0, 1, 2]))
[[  2.   4.   6.]
 [  8.  10.  12.]]


## Lineárna algebra

* Je potrebné najskôr importovať `numpy.linalg`
```
import numpy.linalg as linalg
```
* Inverzia regulérnej matice:
```
M = np.array( [ [1., 2. ], [5., 6.] ] )
I = linalg.inv(M)
```
* Hodnosť matice:
```
r = linalg.matrix_rank(M)
```
* Riešenie systému rovníc Ax=b (matica A štvorcová):
```
A = np.array( [ [1., 2. ], [5., 6.] ] )
b = np.array( [ [3.], [4.] ])
x = linalg.solve(A, b)
```
* Riešenie systému rovníc Ax=b (matica A neštvorcová):
```
x = linalg.lstsq(A, b)
```
* Zistenie vlastných čísel a vektorov:
```
V,D = linalg.eig(A)
```

In [95]:
import numpy.linalg as linalg
M = np.array( [ [1., 2. ], [5., 6.] ] )
I = linalg.inv(M)
print(I)
r = linalg.matrix_rank(M)
print(r)

A = np.array( [ [1., 2. ], [5., 6.] ] )
b = np.array( [ [3.], [4.] ])
x = linalg.solve(A, b)
print(x)

V,D = linalg.eig(A)
print(V)
print(D)

[[-1.5   0.5 ]
 [ 1.25 -0.25]]
2
[[-2.5 ]
 [ 2.75]]
[-0.53112887  7.53112887]
[[-0.79402877 -0.2928046 ]
 [ 0.60788018 -0.9561723 ]]
