Vytvorte stĺpcový vektor `x` obsahujúci čísla od 1 po 5.

Na obrazovku vypíšte rozmery vektora `x` v tvare

```
Vektor ma XXX riadkov a YYY stlpcov
```

Vektor ma 5 riadkov a 1 stlpcov


Vytvorte maticu `Z = x*x'` a vypíšte ju na obrazovku

[[  1.   2.   3.   4.   5.]
 [  2.   4.   6.   8.  10.]
 [  3.   6.   9.  12.  15.]
 [  4.   8.  12.  16.  20.]
 [  5.  10.  15.  20.  25.]]


Vypíšte prvok ležiaci na 2. riadku a 3. stĺpci matice `Z`

6.0


Vypíšte druhý riadok matice `Z`

[  2.   4.   6.   8.  10.]


Vytvorte maticu skladajúcu sa z 2. a 4. riadka matice Z a z jej 1., 3. a 5. stĺpca

[[  2.   6.  10.]
 [  4.  12.  20.]]


Zistite, či je matica `Z` invertovateľná. Použite dva spôsoby:
1. matica je invertovateľná, ak jej hodnosť je totožná s jej rozmerom
2. matica je invertovateľná, ak jej vlastné čísla nie sú nulové

V oboch prípadoch musí byť, samozrejme, matica štvorcová. Túto podmienku tiež zahrňte do programu.

False
False
True
False
True
True


Postup z predošlej úlohy aplikujte na nasledovné matice a pre každú z nich vypíšte jej hodnosť, vlastné čísla a či je invertovateľná. Uvažujte nasledovné matice:
```
M1 = np.zeros((2, 2))
M2 = np.eye(3)
M3 = np.ones((3, 3))
M4 = np.array( [ [1., 2.], [3., 4.] ])
M5 = np.array( [ [1., 2.], [5., 6.] ])
```

[-0.53112887  7.53112887]
[[-0.79402877 -0.2928046 ]
 [ 0.60788018 -0.9561723 ]]
[ 0.4217316  -0.32286272]


Zistite riešenie systému rovníc
```
 x1 + 2*x2 + x3 = 2
        x2 + x3 = 4
-x1 +   x2 + x3 = 5       
```

Programovo vykonajte skúšku správnosti výsledku z predošlej úlohy

Uvažujme vektor `x` obsahujúci čísla od 1 po 5 (ako čísla s desatinnou čiarkou). Vytvorte maticu `M` v nasledovnom tvare:
```
[ x1^2 x1 1 ]
[ x2^2 x2 1 ]
[ x3^2 x3 1 ]
[ x4^2 x4 1 ]
[ x5^2 x5 1 ]
```

Vytvorte maticu `M'*M` a zistite, či je invertovateľná. Ak je, na obrazovku vypíšte jej inverziu.

Uvažujme vektor `x` obsahujúci čísla od 1 po 5 (ako čísla s desatinnou čiarkou) a vektor `y` obsahujúci hodnoty `[1, 0.5, 3, 4.2, 7.8]`. Zistite parametre funkcie `f = a*x^2+b*x+c`, ktorá najpresnejšie aproximuje dané body, teda minimalizuje sumu štvorcov odchýliek medzi `y_i` a `f(x_i)`.

Očakávaný výsledok:
```
Aproximacna funkcia: 0.4949*x^2 - 1.2271*x + 1.5600
Suma stvorcov odchyliek: 0.9503
```